[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/debug",
    "crates/recon",
    "crates/translation_dump",
    "crates/unlock_fps",
    "crates/runtime",
    "crates/testing/fake-unity-framework",
]
exclude = [
    "experiments/entry-patch",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/Pixdane/ShinySongTools"

[workspace.dependencies]
corelib = { package = "core", path = "crates/core" }
debug = { path = "crates/debug" }
recon = { path = "crates/recon" }
translation_dump = { path = "crates/translation_dump" }
unlock_fps = { path = "crates/unlock_fps" }

bevy_ecs = { version = "0.19.1", default-features = false, features = ["std"] }
il2cpp-bridge-rs = "=0.1.4"
libc = "0.2"
toml = "0.9"
crossbeam-queue = "0.3"
crossbeam-utils = "0.8"
thiserror = "2"
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "std", "registry"] }
tracing-os-layer = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

trybuild = "1"

[profile.release]
panic = "unwind"

[profile.dev]
panic = "unwind"
